# Generated by Django 5.2 on 2025-04-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='estado',
        ),
        migrations.AddField(
            model_name='actividad',
            name='audios',
            field=models.FileField(blank=True, null=True, upload_to='actividades_audios/'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='actividades_imagenes/'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='audios',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos_audios/'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='es_version_original',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='mantenimientos_imagenes/'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='actividades',
            field=models.ManyToManyField(to='tasks.actividad'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='responsable',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('operador', 'Operador'), ('supervisor', 'Supervisor')], max_length=20),
        ),
    ]
