# Generated by Django 5.2 on 2025-04-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_actividad_estado_actividad_audios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='audios',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='audios',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='imagenes',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='observaciones',
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='tasks.actividad')),
                ('mantenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='tasks.mantenimiento')),
            ],
        ),
    ]
